name: Docker Build and Upload CI

on:
  push:
    branches:
      - 'main'
  
permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.GAVINHALAB_DOCKERHUB_USERNAME }}
          password: ${{ secrets.GAVINHALAB_DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        run: docker build --platform linux/amd64 -t gavinhalab/ichorcna:3.0.0 -f Docker/Dockerfile --push .



